sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
script:
  - npm start validate
after_success:
  - npm install -g codecov semantic-release
  - codecov
  # disable auto-releasing until we're ready for this thing to go live
  # - semantic-release pre && npm publish && semantic-release post
branches:
  only:
    - master
